#!/usr/bin/env bash
# a script to display information about sudbomains of biophile.tech DNS

sub_domain_list=(www lb-01 web-01 web-02)

echo_dig () {
    dig "${2}.${1}" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain '$2' is a " $4 " record and points to "$5}'
} 

if [ -z "$2" ]
then
    for sub in "${sub_domain_list[@]}"; do
        echo_dig "$1" "$sub"
    done
else
    echo_dig "$1" "$2"
fi
exit 0
