#!/usr/bin/env bash
# install and configure ngix
# and make a custome front page

sudo apt-get -y update
sudo apt-get -y install nginx 
sudo ufw allow "Nignx HTTP"
echo "Hello World!" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a \\tlocation /redirect_me { \n \t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}' /etc/nginx/sites-enabled/default
sudo service nginx restart
