#!/usr/bin/env bash
# configures the local Nginx to set a header value
# for X-Served-By to the hostname of the server

sudo sed -i "27 i\ \tadd_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default
sudo service nginx restart
