#!/usr/bin/env bash
# configures a load balancer to to use a roundrobin algorithm
# to decide between two servers

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y update

sudo apt-get -y install haproxy=2.7.\*
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 94417-web-01 54.144.137.83:80 check\n\tserver 94417-web-02 100.26.20.157:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
