#!/usr/bin/env bash
# this is a scrpit that prints the string "Best School" 8 times and
# prints hi on the 9th iteration befor printing best scchool once more
i=1                                                                                                                                     
while [ "$i" -le 10 ]; 
do       
       	echo "Best School"                                                                                                              
        if [ "$i" -eq 9 ]
	then
		echo "Hi"
	fi
	(( i++ ))                                                                                                                         
done 
