#!/usr/bin/env bash                                                                                                                     
# this is a scrpit that prints the string "Best School" a total of 8 times and
# prints "bad luck" on the 4th iteration and prints "good lluck" on the 8th iteration
i=1                                                                                                                                     
while [ "$i" -le 10 ];                                                                                                                  
do                                                                                                                                      
        if [ "$i" -eq 4 ]                                                                                                               
        then                                                                                                                            
                echo "bad luck"        
	elif [ "$i" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
        fi
	(( i++ ))
done
