#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes
i=1
while [ "$i" -le 13 ]
do
	j=1
	while [ "$j" -le 59 ]
	do
		echo "$j"
		(( j++ ))
	done
	if [ "$i" -ne 13 ]
	then
		echo "Hour: $i"
	fi
		(( i++ ))
done
