#!/usr/bin/env bash                                                                                                                     
# this is a scrpt that prints thefiles in the current directory                                                                         
dir="$(ls)"                                                                                                                             
for  i in $dir                                                                                                                          
do
	echo "$i" | cut -d '-' -f2
done
